ARG RUBY_VERSION=3.3.1
FROM docker.io/library/ruby:${RUBY_VERSION}-slim

WORKDIR /rails

RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y \
      build-essential \
      curl \
      git \
      libpq-dev \
      nodejs \
      npm \
      pkg-config \
      postgresql-client && \
    rm -rf /var/lib/apt/lists /var/cache/apt/archives

RUN gem install foreman

ENV BUNDLE_PATH=/usr/local/bundle \
    BUNDLE_JOBS=4 \
    BUNDLE_RETRY=3

COPY Gemfile Gemfile.lock package.json package-lock.json ./

RUN bundle install && npm install

COPY bin/docker-dev-entrypoint /usr/local/bin/docker-dev-entrypoint
RUN chmod +x /usr/local/bin/docker-dev-entrypoint

EXPOSE 3000

ENTRYPOINT ["docker-dev-entrypoint"]
CMD ["bin/dev"]
